In [51]:
import pandas as pd

In [52]:
logic_ans = pd.read_csv("Logic_Answers.csv")
logic_qn = pd.read_csv("Logic_Questions.csv")
stats_ans = pd.read_csv("Statistics_Answers.csv")
stats_qn = pd.read_csv("Statistics_Questions.csv")

In [53]:
logic_ans["Number"] = logic_ans["Item Number"].str.extract(r"(\d+\.\d+)", expand=False)
logic_qn["Number"] = logic_qn["Question Number"].str.extract(r"(\d+\.\d+)", expand=False)

In [54]:
logic_merge = logic_qn.merge(logic_ans, on="Number", how="outer")
logic_merge.rename(columns={"Content_x":"Question","Content_y":"Answer", "Item Number":"Answer Number"}, inplace=True)

In [55]:
logic_merge.to_csv("Combined_Logic.csv")
logic_merge

,Question Number,Question,Number,Answer Number,Answer
0,Question 1.1,/_387 You are given two glass jugs. Each conta...,1.1,Answer 1.1,This question has appeared over and over again...
1,Question 1.10,/_387 Picture a 10 ×10×10 “macro-cube” ﬂoating...,1.10,Answer 1.10,The 10 ×10 macro-cube question has been very p...
2,Question 1.11,"/_387 There are two cities, A and B, 1,000 mil...",1.11,Answer 1.11,If not for the ability to stop and dump apples...
3,Question 1.12,/_387 How many degrees (if any) are there in t...,1.12,Answer 1.12,People have given me answers to this one rangi...
4,Question 1.13,/_387 What is the ﬁrst time after 3 pmwhen the...,1.13,Answer 1.13,"I present three diﬀerent solutions: ﬁrst, an a..."
...,...,...,...,...,...
92,Question 1.93,"/_387Id on o th a v eat o a s t e r ,b u tIh a...",1.93,Answer 1.93,Like so many of the simpler quantitative inter...
93,Question 1.94,Consider a wire-frame 1 ×1 cube. Label one ver...,1.94,Answer 1.94,"Let me label the vertices closest to Aas 1, 2,..."
94,Question 1.95,Prove that there are inﬁnitely many prime numb...,1.95,Answer 1.95,I give two related proofs that inﬁnitely many ...
95,Question 1.96,"Show that when given any positive integer n, t...",1.96,Answer 1.96,Following on from the answer to the previous q...
96,Question 1.97,"/_387 Finally, can the mean of two consecutive...",1.97,Answer 1.97,Can the mean of two consecutive prime numbers ...

In [56]:
stats_ans["Number"] = stats_ans["Item Number"].str.extract(r"(\d+\.\d+)", expand=False)
stats_qn["Number"] = stats_qn["Question Number"].str.extract(r"(\d+\.\d+)", expand=False)
stats_merge = stats_qn.merge(stats_ans, on="Number", how="outer")
stats_merge.rename(columns={"Content_x":"Question","Content_y":"Answer", "Item Number":"Answer Number"}, inplace=True)
stats_merge.isna().sum()

Question Number    0
Question           0
Number             0
Answer Number      0
Answer             0
dtype: int64

In [57]:
stats_merge.to_csv("Combined_Stats.csv")
stats_merge

,Question Number,Question,Number,Answer Number,Answer
0,Question 4.1,A breakfast cereal company gives away a free t...,4.1,Answer 4.1,"Before giving an algebraic answer, I think you..."
1,Question 4.10,/_387 (**) Two sealed envelopes are handed out...,4.10,Answer 4.10,This has been a very popular question. Assume ...
2,Question 4.11,They call this the “World Series” problem in t...,4.11,Answer 4.11,This is a very common question and has been in...
3,Question 4.12,"/_387 You have three children, but only one ap...",4.12,Answer 4.12,There are many diﬀerent possible answers; I gi...
4,Question 4.12,"/_387 You have three children, but only one ap...",4.12,Answer 4.12,"If you toss the coin twice and\ngetTT,t h e ny..."
...,...,...,...,...,...
63,Question 4.6,/_387 Consider the following game. The player ...,4.6,Answer 4.6,This sort of question is common. Begin by calc...
64,Question 4.60,What is a p-value?\n©2021 Timothy Falcon Crack...,4.60,Answer 4.60,"Before deﬁning the p-value, let us discuss sta..."
65,Question 4.7,Ia mg o i n gt ot o s sf o u rc o i n s . Y o ...,4.7,Answer 4.7,"Ig i v ea ne l e g a n ta n s w e rﬁ r s t ,a ..."
66,Question 4.8,I will roll a single die no more than three ti...,4.8,Answer 4.8,Another die-rolling question; they are very po...
67,Question 4.9,The correlation between XandYisρ.W h a t i s t...,4.9,Answer 4.9,The correlation is still ρ.A d d i n g a c o n...

In [58]:
print("Qns\n")
print(stats_merge.iloc[0,1]+"\n")
print("Ans\n")
print(stats_merge.iloc[0,4])

Qns

A breakfast cereal company gives away a free toy in each box of
cereal. There are four diﬀerent toys. How many boxes do you expect to have
to buy in order to get all four toys?

Ans

Before giving an algebraic answer, I think you should have a guess.
This shows that you can guess, and it gives you a baseline number to compare
your algebraic answer with, which could produce a warning red ﬂag if you
make a mistake with the algebra.
Obviously, when you buy your ﬁrst cereal box, you get one of the four toys
with probability one on that draw. As you acquire diﬀerent toys, however, the
likelihood that you get the next one in only one draw falls. For example, by
the time you already have three of the four toys, you only have one chance in
four that the next draw will give you the fourth. So, the absolute minimum
number of purchases required is four, but you could buy 100 boxes, and not
get all four toys—though this latter outcome seems very unlikely. Weighing
these odds up, my gut instinct is that it should take something like 10 draws
on average to get all four toys.
Now let us solve the problem algebraically. Consider ﬁrst the more general
problem of having Ttoys. (As an aside, note that the answer we seek must
also be the same as if we roll a T-sided die and we ask how many rolls do we
expect to have to make in order to have seen all Tsides appear.)
Let us give a simple recursion argument. Suppose that Tis the number of
diﬀerent toys we seek. Let us suppose that we are currently attempting to
get our tthtoy, having already found ( t−1) diﬀerent toys. We can immedi-
ately see that the probability, ptthat we get the tthtoy in only one draw is
[T−(t−1)]/T. For example, when seeking the ﬁrst toy, p1=1 ,a n dw h e n
seeking the second toy, p2=(T−1)/T,a n ds oo n .
LetNtbe the number of draws required to obtain the tthtoy, having already
found ( t−1) diﬀerent toys. Then there is probability ptthat we get the tth
toy in one draw, and probability (1 −pt)t h a tw eh a v et od r a wa g a i n . G i v e n
independence of outcomes on diﬀerent draws, it follows that we have a simple
recursion for E(Nt)g i v e nb y
E(Nt)=pt·1+( 1 −pt)·[1 +E(Nt)].
©2021 Timothy Falcon Crack 287 All Rights Reserved Worldwide